version: '3'

services:
  unethicalite-discord:
    container_name: repo-poller
    hostname: repo-poller
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    tty: true
    stdin_open: true