version: '3'

services:
  repo-poller:
    container_name: repo-poller
    hostname: repo-poller
    build: .
    ports:
      - "8083:8083"
    env_file:
      - .env
    tty: true
    stdin_open: true
    networks:
      - unethicalite-docker
networks:
  unethicalite-docker:
    external: true